services:
  # MongoDB for Development
  mongodb:
    image: mongo:7.0
    container_name: vote-secret-dev-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword123
      MONGO_INITDB_DATABASE: vote_secret_dev
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - vote-secret-dev
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Development Backend (optional - can run locally)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vote-secret-dev-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://admin:devpassword123@mongodb:27017/vote_secret_dev?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - vote-secret-dev
    command: ["python", "-m", "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

networks:
  vote-secret-dev:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local