version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: vote-secret-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=vote_secret_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - vote-secret-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vote-secret-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=vote_secret_db
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - vote-secret-network
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vote-secret-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vote-secret-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn start

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  vote-secret-network:
    driver: bridge